
# Some of these are riscv or host target specific, but it does not harm at present to
# overset cmake values
inputs:
  build_type:
    description: 'build type e.g Release, ReleaseAssert (default ReleaseAssert)'
    default: ReleaseAssert

