name: run planned tests for llvm 19
on:
  pull_request:
    paths:
      - '.github/workflows/planned_testing_caller_19.yml'
  schedule:
    # Run Sun, Tues, Thurs Sat at 7pm
    - cron: '0 19 * * 0,2,4,6'


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  L19_:
    if: github.repository == 'uxlfoundation/oneapi-construction-kit' || github.event_name != 'schedule'
    uses: ./.github/workflows/planned_testing_caller.yml
    with:
      llvm_version: '19'
      llvm_branch: 'release/19.x'
      use_llvm_github_cache: true
      # We can set ock, test_sycl_cts etc here optionally if this is used as a pull request.
      # Any with parameters below this is intended for local testing and should not be merged.
      # target_list: '[ "host_x86_64_linux" ]'
      ock: true
      native_cpu: true
      test_tornado: false
      test_sycl_cts: false
      test_sycl_e2e: true      
      test_opencl_cts: false
      run_internal: false
      run_external: true
      build_llvm: false

      # # These can be set to a workflow run-id to download from a previous workflow. This can be seen from
      # # the action run of a job or workflow
      # # e.g. https://github.com/uxlfoundation/oneapi-construction-kit/actions/runs/<run-id>/.....
      download_ock_artefact: host_x86_64_linux=14602541524;host_aarch64_linux=14602541524;host_riscv64_linux=14602541524
      download_dpcpp_artefact: host_x86_64_linux=14602541524;host_aarch64_linux=14602541524;host_riscv64_linux=14602541524
      download_sycl_cts_artefact: host_x86_64_linux=14602541524;host_aarch64_linux=14602541524;host_riscv64_linux=14602541524
