# Simple workflow for running internal ock tests
name: Run ock internal tests
on:
  workflow_call:
    inputs:
      is_pull_request:
        required: false
        type: boolean
        default: true
      llvm_source:
        required: false
        description: 'method of sourcing llvm (install or cache), currently advisory until all converted'
        type: string
        default: 'install'
      llvm_previous:
        required: true
        type: string
        description: 'previous llvm version to for those jobs tied to previous.'
      llvm_current:
        required: true
        type: string
        description: 'previous llvm version to for those jobs tied to current.'
      github_token:
        type: string
        description: 'gh token for downloading artifacts - only needed if we want llvm from a previous workflow'
        default: 'TOKEN_NOT_SET'
      target_list:
        required: false
        type: string
        default: '[ "host_x86_64_linux",
                    "host_aarch64_linux",
                    "host_riscv64_linux",
                    "host_i686_linux",
                    "host_refsi_linux",
                    "host_x86_64_windows" ]'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      is_pull_request:
        required: false
        type: bool
        default: true
      llvm_source:
        required: false
        type: string
        description: 'method of sourcing llvm (install or cache), currently advisory until all converted'
        default: 'install'
      llvm_previous:
        required: false
        type: string
        description: 'previous llvm version to for those jobs tied to previous.'
      llvm_current:
        required: false
        type: string
        description: 'previous llvm version to for those jobs tied to current.'        

permissions:
  packages: read

jobs:

  # build and run host x86_64, execute UnitCL and lit tests and build and run offline
 run_host_x86_64:
    # runs-on: uxl-gpu-xlarge #ubuntu-22.04
    runs-on: ubuntu-22.04
    # container:
    #   image: ghcr.io/uxlfoundation/ock_ubuntu_22.04:latest
    #   volumes:
    #     - ${{github.workspace}}:${{github.workspace}}
    steps:
      - name: get stats
        run: |
          lscpu
          uname -a
