# Calling workflow for running PR style tests
name: Run ock tests for PR style testing
on:
  pull_request:
    paths:
      - 'source/**'
      - 'clik/**'
      - 'modules/**'
      - 'examples/**'
      - 'cmake/**'
      - 'hal/**'
      - '.github/actions/do_build_ock/**'
      - '.github/actions/setup_build/**'
      - '.github/workflows/run_ock_internal_tests.yml'
      - '.github/workflows/run_pr_tests_caller.yml'
      - 'CMakeLists.txt'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-prs:
    name: Call PR testing on schedule
    uses: ./.github/workflows/run_ock_internal_tests.yml
    with:
      is_pull_request: true
      llvm_source: install
      llvm_previous: 19
      llvm_current: 20
      target_list: '[ "host_x86_64_windows" ]'


